parameters:
#    whony_base.example.class: Whony\BaseBundle\Example

services:
#    whony_base.example:
#        class: %whony_base.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
