WhonyBaseBundle:
    resource: "@WhonyBaseBundle/Resources/config/routing.yml"
    prefix:   /

WhonyCatalogBundle:
    resource: "@WhonyCatalogBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
